### PR TITLE
Added Open Street Maps Id to everything, so we can request boundries …

### PR DESCRIPTION
**Pull request by seddik**
…and all information needed

we will add the Open street maps gradually, when we finish all cities we will request the cities boundries geometry for everything.

### CODE REVIEW

**Comment by seddik** [comment]
Added OSM ID for TOUGGOURT(55) and ADRAR (01)

**Comment by seddik** [comment]
@bensialih I don't have write access so I can't do anything about it

**Comment by bensialih** [comment]
@seddik ive added you as a collaborator

**Comment by bensialih** [comment]
with regards to using the issues, updating the wilayas has to be done when the wilaya is complete.
Is that when the gps coordinates are done or when the osm id is assigned.
Also I can finish assigning all the wilayas osm ids except one missing city.
I will do my best to keep it updated but let me know if this should be done when gps assignment or osm?

**Pull request merged**
