### PR TITLE
polygon gps coords for borders from openstreets

### PR DESCRIPTION
**Pull request by bensialih**

### CODE REVIEW

**Comment by seddik** [comment]
the id here is used as a field, it may cause some problems for scripting and some languages like php, to use those values you need to do the following

`$mygeo = $data[0]->{22};` or something, I think the rightway to do it is to use the following

```
"id":22,
"geo":[123,3245],[123,3245],[123,3245]
```

image

**Comment by seddik** [comment]
@bensialih it is better to invert longitude and latitude, for example for ID = 22 it should be 

```
"22": [
            [
                27.451784,
                0.2413869
            ],
```

image

image

**Comment by seddik** [comment]
@bensialih  I've added two links, one with the current data format, and one when you change the format and invert the coordinates

the current one is :
https://algeriacities.oecole.com/geo

the one when you change the format 
https://algeriacities.oecole.com/geonew

you can append the id to check just one City


image

image

**Review by seddik — CHANGES_REQUESTED** [review]
the changes needs to be done are in the PR comments

**Comment by bensialih** [comment]
Is this ready to merge. I dont think it needs anything else unless its missing any co-ordinates

**Comment by bensialih** [comment]
changes made to data structure.
Reduced file size by removing spaces

**Comment by bensialih** [comment]
Im loving your UI work. @seddik 
Can we update the map to reflect the new key: value changes, then I think its ready to merge

**Comment by seddik** [comment]
@bensialih thnx, I was busy in the previous days, I'll resume today inchallah.

**Pull request merged**
